=== CommonSenseDTU/schemas/schema/omh/smoking-experience-1.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "This schema represents the random experience questions for the MD2K smoking detection study.",
    "type": "object",
    "references": [
        {
            "description": "This is a custom questionnaire."
        },
        {
            "description": "The SNOMED code represents Tobacco smoking behavior (finding)",
            "url": "http://purl.bioontology.org/ontology/SNOMEDCT/365981007"
        }
    ],
    "definitions": {
        "date_time": {
            "$ref": "date-time-1.x.json"
        },
        "generic_question_yesno": {
            "$ref": "generic-question-yesno-1.x.json"
        },
        "generic_question_text": {
            "$ref": "generic-question-text-1.x.json"
        }
    },
    "properties": {
        "items": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "allOf": [
                        {
                            "$ref": "#/definitions/generic_question_yesno"
                        },
                        {
                            "properties": {
                                "question": {
                                    "enum": [
                                        {
                                            "code": "EXPSmo",
                                            "text": "Have you smoked since the last time you recorded anything on the phone?"
                                        }
                                    ]
                                },
                                "start_date_time": {
                                    "$ref": "#/definitions/date_time"
                                },
                                "end_date_time": {
                                    "$ref": "#/definitions/date_time"
                                }
                            }
                        }
                    ]
                },
                {
                    "type": "object",
                    "allOf": [
                        {
                            "$ref": "#/definitions/generic_question_text"
                        },
                        {
                            "properties": {
                                "question": {
                                    "description": "If EXPSmo = 1, then EXPSmoText is displayed.",
                                    "enum": [
                                        {
                                            "code": "EXPSmoText",
                                            "text": "How did it feel to inhale that first puff?"
                                        }
                                    ]
                                }
                            }
                        }
                    ]
                }
            ]
        },
        "first_delivered_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "start_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "last_available_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "delay_start_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "delay_end_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "status": {
            "type": "string",
            "enum": ["successful","missed","abandoned"]
        }
    },
    "required": ["first_delivered_date_time","status"]
}

=== CommonSenseDTU/schemas/test-data/omh/smoking-experience/1.0/shouldPass/missed-questionnaire.json
{
    "items": [
        {
            "question": {
                "label": "EXPSmo",
                "text": "Have you smoked since the last time you recorded anything on the phone?"
            },
            "start_date_time": "2015-02-05T07:24:10Z"
        }
    ],
    "first_delivered_date_time": "2015-02-05T07:24:00Z",
    "last_available_date_time": "2015-02-05T07:24:00Z",
    "status": "missed"
}

=== CommonSenseDTU/schemas/test-data/omh/smoking-experience-too/1.0/shouldPass/completed-questionnaire-too.json
{
    "items": [
        {
            "question": {
                "label": "EXPSmo",
                "text": "Have you smoked since the last time you recorded anything on the phone?"
            },
            "answer": {
                "code": 1,
                "text": "yes"
            },
            "date_time_asked": "2015-02-05T07:24:10Z",
            "date_time_answered": "2015-02-05T07:24:40Z"
        },
        {
            "question": {
                "label": "EXPSmoTime",
                "text": "Approximately how long ago did you take the first puff from that cigarette?"
            },
            "answer": {
                "value": 30,
                "unit": "min"
            },
            "date_time_asked": "2015-02-05T07:24:50Z",
            "date_time_answered": "2015-02-05T07:25:00Z"
        },
        {
            "question": {
                "label": "EXPSmoText",
                "text": "How did it feel to inhale that first puff?"
            },
            "answer": "Bad taste in my mouth",
            "date_time_asked": "2015-02-05T07:25:10Z",
            "date_time_answered": "2015-02-05T07:25:40Z"
        },
        {
            "question": {
                "label": "DDTFB",
                "text": "Please check the hour blocks when you took 1 or more puffs today."
            },
            "answer": [
                "1pm-2pm",
                "4pm-5pm",
                "7pm-8pm"
            ],
            "date_time_asked": "2015-02-05T07:27:10Z",
            "date_time_answered": "2015-02-05T07:27:40Z"
        },
        {
            "question": {
                "label": "SUrge",
                "text": "How strong is your urge to smoke right now?"
            },
            "answer": {
                "code": 2,
                "text": "moderate"
            },
            "date_time_asked": "2015-02-05T07:26:10Z",
            "date_time_answered": "2015-02-05T07:26:40Z"
        },
        {
            "question": {
                "label": "SStress1r",
                "text": "I feel cheerful."
            },
            "answer": {
                "code": 2,
                "text": "no"
            },
            "date_time_asked": "2015-02-05T07:27:10Z",
            "date_time_answered": "2015-02-05T07:27:40Z"
        },
        {
            "question": {
                "label": "SStress2r",
                "text": "I feel happy."
            },
            "answer": {
                "code": 1,
                "text": "NO"
            },
            "date_time_asked": "2015-02-05T07:28:10Z",
            "date_time_answered": "2015-02-05T07:28:40Z"
        }
    ],
    "first_delivered_date_time": "2015-02-05T07:24:00Z",
    "start_date_time": "2015-02-05T07:24:10Z",
    "status": "successful"
}

=== CommonSenseDTU/schemas/test-data/omh/smoking-experience/1.0/shouldPass/completed-questionnaire-too.json
{
    "items": [
        {
            "question": {
                "code": "EXPSmo",
                "text": "Have you smoked since the last time you recorded anything on the phone?"
            },
            "answer": {
                "code": 1,
                "text": "yes"
            },
            "start_date_time": "2015-02-05T07:24:10Z",
            "end_date_time": "2015-02-05T07:24:40Z"
        },
        {
            "question": {
                "code": "EXPSmoTime",
                "text": "Approximately how long ago did you take the first puff from that cigarette?"
            },
            "answer": {
                "value": 30,
                "unit": "min"
            },
            "start_date_time": "2015-02-05T07:24:50Z",
            "end_date_time": "2015-02-05T07:25:00Z"
        },
        {
            "question": {
                "code": "EXPSmoText",
                "text": "How did it feel to inhale that first puff?"
            },
            "answer": "Bad taste in my mouth",
            "start_date_time": "2015-02-05T07:25:10Z",
            "end_date_time": "2015-02-05T07:25:40Z"
        },
        {
            "question": {
                "code": "SUrge",
                "text": "How strong is your urge to smoke right now?"
            },
            "answer": {
                "code": 2,
                "text": "moderate"
            },
            "start_date_time": "2015-02-05T07:26:10Z",
            "end_date_time": "2015-02-05T07:26:40Z"
        }
    ],
    "first_delivered_date_time": "2015-02-05T07:24:00Z",
    "start_date_time": "2015-02-05T07:24:10Z",
    "status": "successful"
}
