=== CommonSenseDTU/schemas/schema/omh/smoke-craving-lam-1.0.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "This schema represents the Lam et al. self-report smoke craving questionnaire.",
    "type": "object",
    "references": [
        {
            "description": "Lam et al. (2014)"
        },
        {
            "description": "The SNOMED code represents Tobacco smoking behavior (finding)",
            "url": "http://purl.bioontology.org/ontology/SNOMEDCT/365981007"
        }
    ],
    "definitions": {
        "date_time": {
            "$ref": "date-time-1.x.json"
        },
        "generic_categorical_question": {
            "$ref": "generic-categorical-question-1.x.json"
        },
        "categorical_item": {
            "type": "object",
            "properties": {
                "question": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        },
                        "text": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "text"
                    ]
                },
                "answer": {
                    "type": "object",
                    "enum": [
                        {
                            "code": 0,
                            "text": "no urge"
                        },
                        {
                            "code": 1,
                            "text": "weak"
                        },
                        {
                            "code": 2,
                            "text": "moderate"
                        },
                        {
                            "code": 3,
                            "text": "strong"
                        },
                        {
                            "code": 4,
                            "text": "severe"
                        }
                    ],
                    "additionalItems": false
                },
                "start_date_time": {
                    "$ref": "#/definitions/date_time"
                },
                "end_date_time": {
                    "$ref": "#/definitions/date_time"
                }
            },
            "additionalProperties": false
        }
    },
    "properties": {
        "items": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "allOf": [
                        {
                            "$ref": "#/definitions/generic_categorical_question"
                        },
                        {
                            "properties": {
                                "question": {
                                    "enum": [
                                        {
                                            "code": "SUrge",
                                            "text": "How strong is your urge to smoke right now?"
                                        }
                                    ]
                                },
                                "answer": {
                                    "enum": [
                                        {
                                            "code": 0,
                                            "text": "no urge"
                                        },
                                        {
                                            "code": 1,
                                            "text": "weak"
                                        },
                                        {
                                            "code": 2,
                                            "text": "moderate"
                                        },
                                        {
                                            "code": 3,
                                            "text": "strong"
                                        },
                                        {
                                            "code": 4,
                                            "text": "severe"
                                        }
                                    ],
                                    "additionalItems": false
                                },
                                "start_date_time": {
                                    "$ref": "#/definitions/date_time"
                                },
                                "end_date_time": {
                                    "$ref": "#/definitions/date_time"
                                }
                            },
                            "additionalProperties": false
                        }
                    ]
                }
            ],
            "additionalItems": false
        },
        "first_delivered_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "start_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "last_available_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "delay_start_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "delay_end_date_time": {
            "$ref": "#/definitions/date_time"
        },
        "status": {
            "type": "string",
            "enum": ["successful","missed","abandoned"]
        },
        "trigger": {
            "type": "string",
            "enum": ["random","event","signal","end of day"]
        }
    },
    "required": ["first_delivered_date_time","status"],
    "additionalProperties": false
}

=== CommonSenseDTU/schemas/test-data/omh/smoking-experience-custom-old/1.0/shouldPass/completed-questionnaire.json
{
    "items": [
        {
            "question": {
                "code": "EXPSmo",
                "text": "Have you smoked since the last time you recorded anything on the phone?"
            },
            "answer": {
                "code": 1,
                "text": "yes"
            },
            "start_time_frame": {
                "date_time": "2015-02-05T07:22:10Z"
            },
            "end_time_frame": {
                "date_time": "2015-02-05T07:25:10Z"
            }
        },
        {
            "question": {
                "code": "EXPSmoLat",
                "text": "Approximately how long ago did you take the first puff from that cigarette?"
            },
            "answer": 60,
            "start_time_frame": {
                "date_time": "2015-02-05T07:27:10Z"
            },
            "end_time_frame": {
                "date_time": "2015-02-05T07:30:10Z"
            }
        },
        {
            "question": {
                "code": "EXPInt",
                "text": "Have you received a stress-reduction suggestion on your watch since the last time you recorded anything on the phone?"
            },
            "answer": {
                "code": 1,
                "text": "yes"
            },
            "start_time_frame": {
                "date_time": "2015-02-05T07:33:10Z"
            },
            "end_time_frame": {
                "date_time": "2015-02-05T07:36:10Z"
            }
        },
        {
            "question": {
                "code": "EXPIntUse",
                "text": "Did you access any of the stress reduction apps on the phone?"
            },
            "answer": {
                "code": 1,
                "text": "yes"
            },
            "start_time_frame": {
                "date_time": "2015-02-05T07:38:10Z"
            },
            "end_time_frame": {
                "date_time": "2015-02-05T07:42:10Z"
            }
        },
        {
            "question": {
                "code": "EXPIntHelp",
                "text": "How useful did you find the stress reduction app?"
            },
            "answer": {
                "code": 2,
                "text": "somewhat useful"
            },
            "start_time_frame": {
                "date_time": "2015-02-05T07:45:10Z"
            },
            "end_time_frame": {
                "date_time": "2015-02-05T07:50:10Z"
            }
        },
        {
            "question": {
                "code": "EXPIntSR",
                "text": "Did you use any of the stress reduction exercises (with or without the app) since the last time you recorded anything on the phone?"
            },
            "answer": {
                "code": 0,
                "text": "no"
            },
            "start_time_frame": {
                "date_time": "2015-02-05T07:52:10Z"
            },
            "end_time_frame": {
                "date_time": "2015-02-05T08:00:10Z"
            }
        }
    ],
    "first_delivered_date_time": "2015-02-05T07:24:00Z",
    "status": "successful",
    "trigger": "random"
}
