=== CommonSenseDTU/schemas/schema/clinical/new-medication-prescription-1.0.json
{
   "$schema":"http://json-schema.org/draft-04/schema#",

    "description":"This schema represents a medication prescription e.g., atenolol 50 mg, 1 tablet in the morning and 0.5 tablet in the evening for 30 days.",

    "type":"object",

    "definitions": {
        "medication": {
            "$ref": "medication-1.0.json"
        },
        "medication_route": {
            "$ref": "medication-route-1.0.json",
            "default": "oral"
        },
        "medication_dose_unit_value": {
            "$ref": "medication-dose-unit-value-1.0.json"
        },
        "frequency_unit_value": {
            "$ref": "../generic/new-frequency-unit-value-1.0.json"
        },
        "duration_unit_value": {
            "$ref": "../generic/duration-unit-value-1.0.json"
        },
        "expected_time_frame": {
            "$ref": "../generic/expected-time-frame-1.0.json"
        },
        "temporal_relationship_to_meal": {
            "$ref": "temporal-relationship-to-meal-1.0.json"
        },
        "temporal_relationship_to_sleep": {
            "$ref": "temporal-relationship-to-sleep-1.0.json"
        },
        "part_of_day": {
            "$ref": "../generic/part-of-day-1.0.json"
        },
        "day_of_week": {
            "$ref": "../generic/day-of-week-1.0.json"
        },
        "time": {
            "$ref": "../generic/time-1.0.json"
        }
    },

    "properties": {
        "medication":{
            "$ref": "#/definitions/medication"
        },
        "route": {
            "$ref": "#/definitions/medication_route"
        },
        "epoch_duration":{
            "$ref": "#/definitions/duration_unit_value"
        },
        "schedule": {
            "type": "array",
            "description": "A medication can have different schedules (dose and dose recurrence) for different times, hence this is an array.",
            "items": {
                "type": "object",
                "properties": {
                    "dose": {
                        "$ref": "#/definitions/medication_dose_unit_value"
                    },
                    "dose_recurrence": {
                        "$ref": "#/definitions/frequency_unit_value"
                    },
                    "prn_reason": {
                        "type": "string"
                    },

"timing": {
"type": "array",
"description": "A medication can have different schedules (dose and dose recurrence) for different times, hence this is an array.",
"items": {
    "type": "object",
    "properties": {
        "part_of_day": {
"$ref": "#/definitions/part_of_day"
},
"day_of_week": {
"$ref": "#/definitions/day_of_week"
},
"time_of_day": {
"$ref": "#/definitions/time"
},
        "temporal_relationship_to_meal": {
            "$ref": "#/definitions/temporal_relationship_to_meal"
        },
        "temporal_relationship_to_sleep": {
            "$ref": "#/definitions/temporal_relationship_to_sleep"
        }

   }

}
},

                    "epoch_sequence": {
                        "type": "number"
                    }
                },
                "required": ["dose"],
                "anyOf": [
                    {
                        "required": ["dose_recurrence"]
                    },
                    {
                        "required": ["prn_reason"]
                    }
                ]
            }
        },
        "prescription_duration": {
            "oneOf": [
                {
                    "$ref": "#/definitions/duration_unit_value"
                },
                {
                    "$ref": "#/definitions/expected_time_frame"
                },
                {
                    "type": "string",
                    "default": "continuing"
                }
            ]
        }
    },

    "required": ["medication","schedule","prescription_duration"]
}

=== CommonSenseDTU/schemas/sampleData/clinical/new-medication-prescription/1.0/shouldPass/valid-medication-prescription-prn.json
{
    "medication": {
        "generic_name": "Aspirin [Ascriptin]",
        "strength": {
            "value": 500,
            "unit": "mg"
        },
        "rxnorm_code": 830525
    },

    "route": "oral",

    "schedule": [
        {
            "dose": {
                "value": 1,
                "unit": "tablet"
            },
            "dose_recurrence": {
                "number_of_times": 2,
                "time_window": {
                    "value": 1,
                    "unit": "d"
                },
                "time_between_successive_windows": {
                    "value": 1,
                    "unit": "d"
                }
            },
            "timing": [
                {
                    "time_of_day": "08:00:00",
                    "temporal_relationship_to_meal": "after breakfast"
                },
                {
                    "time_of_day": "20:00:00",
                    "temporal_relationship_to_sleep": "before sleeping"
                }
            ]
        },
        {
            "dose": {
                "value": 1,
                "unit": "tablet"
            },
            "prn_reason": "pain"
        }
    ],
    "prescription_duration": {
        "value": 15,
        "unit": "d"
    }
}

=== CommonSenseDTU/schemas/sampleData/clinical/medication-prescription/1.0/shouldPass/valid-medication-prescription-prn.json
{
    "medication": {
        "generic_name": "Aspirin [Ascriptin]",
        "strength": {
            "value": 500,
            "unit": "mg"
        },
        "rxnorm_code": 830525
    },
    "route": "oral",
    "schedule": [
        {
            "dose": {
                "value": 1,
                "unit": "tablet"
            },
            "prn_reason": "pain"
        }
    ],
    "prescription_duration": {
        "value": 3,
        "unit": "Mo"
    }
}

=== CommonSenseDTU/schemas/sampleData/clinical/new-medication-prescription/1.0/shouldPass/valid-medication-prescription-with-daysofweek.json
{
    "medication": {
        "generic_name": "Aspirin [Ascriptin]",
        "strength": {
            "value": 325,
            "unit": "mg"
        },
        "rxnorm_code": 830530
    },
    "route": "oral",

    "schedule": [
        {
            "dose": {
                "value": 1,
                "unit": "tablet"
            },
            "dose_recurrence": {
                "number_of_times": 3,
                "time_window": {
                    "value": 1,
                    "unit": "wk"
                },
                "time_between_successive_windows": {
                    "value": 1,
                    "unit": "wk"
                }
            },
            "timing": [
                {
                    "part_of_day": "morning",
                    "day_of_week": "Monday"
                },
                {
                    "part_of_day": "morning",
                    "day_of_week": "Wednesday"
                },
                {
                    "part_of_day": "morning",
                    "day_of_week": "Friday"
                }
            ]
        },
        {
            "dose": {
                "value": 0.5,
                "unit": "tablet"
            },
            "dose_recurrence": {
                "number_of_times": 1,
                "time_window": {
                    "value": 1,
                    "unit": "wk"
                },
                "time_between_successive_windows": {
                    "value": 1,
                    "unit": "wk"
                }
            },
            "timing": [
                {
                    "part_of_day": "morning",
                    "day_of_week": "Saturday"
                }
            ]
        }
    ],
    "prescription_duration": {
        "value": 6,
        "unit": "Mo"
    }
}

=== CommonSenseDTU/schemas/sampleData/clinical/medication-prescription/1.0/shouldPass/valid-complex-medication-prescription.json
{
    "medication": {
        "trade_name": "Tenormin 50 MG Oral Tablet",
        "strength": {
            "value": 50,
            "unit": "mg"
        },
        "rxnorm_code": 152414
    },

    "route": "oral",

    "schedule": [
        {
            "dose": {
                "value": 1,
                "unit": "tablet"
            },
            "dose_recurrence": {
                "number_of_times": 1,
                "time_window": {
                    "value": 1,
                    "unit": "d"
                },
                "time_between_successive_windows": {
                    "value": 1,
                    "unit": "d"
                }
            }
        },
        {
            "dose": {
                "value": 0.5,
                "unit": "tablet"
            },
            "dose_recurrence": {
                "number_of_times": 1,
                "time_window": {
                    "value": 1,
                    "unit": "d"
                },
                "time_between_successive_windows": {
                    "value": 2,
                    "unit": "d"
                },
                "part_of_day": ["evening"],
                "temporal_relationship_to_sleep": "before sleeping"
            }
        }
    ],
    "prescription_duration": {
        "value": 15,
        "unit": "d"
    }
}

=== CommonSenseDTU/schemas/sampleData/clinical/new-medication-prescription/1.0/shouldPass/valid-chemo-prescription.json
{
    "medication": {
        "trade_name": "Leucovorin 20 MG/ML Injectable Solution",
        "strength": {
            "value": 20,
            "unit": "mg/mL"
        },
        "rxnorm_code": 237788
    },

    "route": "intravenous peripheral",

    "schedule": [
        {
            "dose": {
                "value": 3.675,
                "unit": "mL"
            },
            "dose_recurrence": {
                "number_of_times": 1,
                "time_window": {
                    "value": 1,
                    "unit": "d"
                },
                "time_between_successive_windows": {
                    "value": 1,
                    "unit": "d"
                }
            }
        }
    ],
    "prescription_duration": {
        "value": 5,
        "unit": "d"
    }
}

=== CommonSenseDTU/schemas/sampleData/clinical/medication-prescription/1.0/shouldPass/valid-medication-prescription-with-epoch.json
{
    "medication": {
        "trade_name": "Tenormin 50 MG Oral Tablet",
        "strength": {
            "value": 50,
            "unit": "mg"
        },
        "rxnorm_code": 152414
    },

    "route": "oral",
    "epoch_duration": {
        "value": 2,
        "unit": "d"
    },
    "schedule": [
        {
            "dose": {
                "value": 1,
                "unit": "tablet"
            },
            "dose_recurrence": {
                "number_of_times": 1,
                "time_window": {
                    "value": 1,
                    "unit": "d"
                }
            },
            "epoch_sequence": 1
        },
        {
            "dose": {
                "value": 0.5,
                "unit": "tablet"
            },
            "dose_recurrence": {
                "number_of_times": 1,
                "time_window": {
                    "value": 2,
                    "unit": "d"
                },
                "part_of_day": ["evening"],
                "temporal_relationship_to_sleep": "before sleeping"
            },
            "epoch_sequence": 2
        }
    ],
    "prescription_duration": {
        "value": 15,
        "unit": "d"
    }
}

=== CommonSenseDTU/schemas/sampleData/clinical/medication-prescription/1.0/shouldPass/valid-medication-prescription-dose-prn.json
{
    "medication": {
        "generic_name": "Aspirin [Ascriptin]",
        "strength": {
            "value": 325,
            "unit": "mg"
        },
        "rxnorm_code": 830530
    },

    "route": "oral",

    "schedule": [
        {
            "dose": {
                "value": 1,
                "unit": "tablet"
            },
            "dose_recurrence": {
                "number_of_times": 2,
                "time_window": {
                    "value": 1,
                    "unit": "d"
                }
            }
        },
        {
            "dose": {
                "value": 1,
                "unit": "tablet"
            },
            "prn_reason": "pain"
        }
    ],
    "prescription_duration": {
        "value": 1,
        "unit": "Mo"
    }
}

=== CommonSenseDTU/schemas/sampleData/clinical/medication-prescription/1.0/shouldPass/valid-antibiotic-prescription.json
{
    "medication": {
        "trade_name": "Trimox",
        "strength": {
            "value": 500,
            "unit": "mg"
        },
        "rxnorm_code": 94406
    },

    "route": "oral",

    "schedule": [
        {
            "dose": {
                "value": 1,
                "unit": "tablet"
            },
            "dose_recurrence": {
                "number_of_times": 1,
                "time_window": {
                    "value": 6,
                    "unit": "h"
                },
                "time_between_successive_windows": {
                    "value": 6,
                    "unit": "h"
                }
            }
        }
    ],
    "prescription_duration": {
        "value": 5,
        "unit": "d"
    }
}
